apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-prod
resources:
  - ../../base
nameSuffix: -prod
images:
  - name: quay.io/rhn_support_rhodain1/hello-world
    newTag: v1.0 # A PR will be created to update this tag
